server:
  port: 9000

project:
  id: pmdb-cloud

---

spring:
  profiles: production

  datasource:
    url: jdbc:postgresql://localhost:5432/pmdb_db
    username: pmdb_service

  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: development

