project:
  id: pmdb-cloud

server:
  port: 9000

spring:
  mvc:
    dispatch-options-request:true

---

spring:
  profiles: production

server:
  port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/pmdb_db
    username: pmdb_service

  jpa:
    hibernate:
      ddl-auto: create-drop

---

spring:
  profiles: development

